create table hotel
(
    hotel_id bigint generated by default as identity
        constraint hotel_pkey
            primary key,
    avg_mark double precision,
    convenience varchar(255),
    location varchar(255),
    name varchar(255)
);

alter table hotel owner to postgres;

create table hotel_rating
(
    id bigint generated by default as identity
        constraint hotel_rating_pkey
            primary key,
    count_of_marks integer,
    mark integer,
    hotel_id bigint
        constraint fk8s3ld1j9yamvg7kl0nmvd67rx
            references hotel
);

alter table hotel_rating owner to postgres;

create table room
(
    room_id bigint generated by default as identity
        constraint room_pkey
            primary key,
    accommodation varchar(255),
    comfort varchar(255),
    number_of_room integer not null,
    hotels_hotel_id bigint
        constraint fk2l0g59jbbqciwgn6w76ey09xh
            references hotel,
    hotel_id bigint
        constraint fkdosq3ww4h9m2osim6o0lugng8
            references hotel
);

alter table room owner to postgres;

create table booking
(
    id bigint generated by default as identity
        constraint booking_pkey
            primary key,
    booking_status integer,
    date_chek_in date,
    date_chek_out date,
    hotel_hotel_id bigint
        constraint fkgvvg58wr7xvswtmrtccfpke29
            references hotel,
    room_room_id bigint
        constraint fk9galrp7ppvo5114oolctsta6j
            references room,
    users_user_id bigint
);

alter table booking owner to postgres;

create table common_user
(
    user_id bigint generated by default as identity
        constraint common_user_pkey
            primary key,
    email varchar(255),
    first_name varchar(255),
    passport varchar(255),
    phone_number integer,
    second_name varchar(255),
    user_role integer,
    booking_id bigint
        constraint fk46ajma84ms133w6mhpa8wlo8m
            references booking
);

alter table common_user owner to postgres;

alter table booking
    add constraint fkbejtw8590cotmxmwao5axlmu8
        foreign key (users_user_id) references common_user;

create table hotel_favorites
(
    favorites_id bigint generated by default as identity
        constraint hotel_favorites_pkey
            primary key,
    hotel_hotel_id bigint
        constraint fklmbgk6iph6lg8wgiwp165oylu
            references hotel,
    user_user_id bigint
        constraint fklheokba6vpytjflbtkad745je
            references common_user,
    user_id bigint
        constraint fkq5cfnqdrlheg3jh5mt0a6jf02
            references common_user
);

alter table hotel_favorites owner to postgres;

