server:
  port: 8003
spring:
  liquibase:
    change-log: db/changelog/changelog-master.xml
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5438/hoteldb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  application:
    name: hotel-app
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

