create table booking
(
    id             int8 generated by default as identity,
    booking_status int4,
    date_chek_in   date,
    date_chek_out  date,
    hotel_hotel_id int8,
    room_room_id   int8,
    users_user_id  int8,
    primary key (id)
);

create table common_user
(
    user_id      int8 generated by default as identity,
    email        varchar(255),
    first_name   varchar(255),
    passport     varchar(255),
    phone_number int4,
    second_name  varchar(255),
    user_role    int4,
    booking_id   int8,
    primary key (user_id)
);

create table hotel
(
    hotel_id    int8 generated by default as identity,
    avg_mark    float8,
    convenience varchar(255),
    location    varchar(255),
    name        varchar(255),
    primary key (hotel_id)
);

create table hotel_favorites
(
    favorites_id   int8 generated by default as identity,
    hotel_hotel_id int8,
    user_user_id   int8,
    user_id        int8,
    primary key (favorites_id)
);

create table hotel_rating
(
    id             int8 generated by default as identity,
    count_of_marks int4,
    mark           int4,
    hotel_id       int8,
    primary key (id)
);

create table room
(
    room_id         int8 generated by default as identity,
    accommodation   varchar(255),
    comfort         varchar(255),
    number_of_room  int4 not null,
    hotels_hotel_id int8,
    hotel_id        int8,
    primary key (room_id)
);

alter table if exists booking add constraint FKgvvg58wr7xvswtmrtccfpke29 foreign key (hotel_hotel_id) references hotel;

alter table if exists booking add constraint FK9galrp7ppvo5114oolctsta6j foreign key (room_room_id) references room;

alter table if exists booking add constraint FKbejtw8590cotmxmwao5axlmu8 foreign key (users_user_id) references common_user;

alter table if exists common_user add constraint FK46ajma84ms133w6mhpa8wlo8m foreign key (booking_id) references booking;

alter table if exists hotel_favorites add constraint FKlmbgk6iph6lg8wgiwp165oylu foreign key (hotel_hotel_id) references hotel;

alter table if exists hotel_favorites add constraint FKlheokba6vpytjflbtkad745je foreign key (user_user_id) references common_user;

alter table if exists hotel_favorites add constraint FKq5cfnqdrlheg3jh5mt0a6jf02 foreign key (user_id) references common_user;

alter table if exists hotel_rating add constraint FK8s3ld1j9yamvg7kl0nmvd67rx foreign key (hotel_id) references hotel;

alter table if exists room add constraint FK2l0g59jbbqciwgn6w76ey09xh foreign key (hotels_hotel_id) references hotel;

alter table if exists room add constraint FKdosq3ww4h9m2osim6o0lugng8 foreign key (hotel_id) references hotel;



